[package]
name = "day_seven"
version = "0.1.0"
authors = ["Ben Simpson <ben@elliptic.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
